# Generated by Django 5.1.3 on 2024-11-29 05:26

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberia_app', '0004_remove_formulario_telefono_formulario_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='dia_hora',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='total',
        ),
        migrations.AddField(
            model_name='formulario',
            name='dia',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Día'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
