# Generated by Django 5.1.3 on 2024-11-29 07:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberia_app', '0005_remove_formulario_dia_hora_remove_formulario_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='hora',
        ),
        migrations.AddField(
            model_name='formulario',
            name='dia_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Día y Hora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulario',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveIntegerField(verbose_name='Monto')),
                ('metodo', models.CharField(max_length=20, verbose_name='Método')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberia_app.cita', verbose_name='Cita')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'ordering': ['id'],
            },
        ),
    ]
